name: install_wheels_cuda

on:
  workflow_call:
    inputs:
      setuppypath:
        required: true
        type: string
        description: "path to the dir of the setup.py that should be built."
      
env:
  FILE_PATH: ${{ inputs.setuppypath }}