name: Build Wheels

on:
  push:
    # push on github tags that start with "wheel"
    tags:
      - "wheel*"

jobs:
  flashmm_wheels:
    uses:
      ./m.github/workflows/workflow_build_cuda_wheels.yaml
    with:
      # working-directory: libs/infinity_emb
      setuppath: ${{ github.workspace }}/csrc/flashmm
    secrets: inherit