name: Build Wheels

on:
  push:
    # push on github tags that start with "wheel"
    tags:
      - "wheel*"

jobs:
  flashmm_wheels:
    uses:
      ./.github/workflows/workflow_build_cuda_wheels.yaml
    with:
      setuppypath: ${{ github.workspace }}/csrc/flashmm
    secrets: inherit